apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: drkiq_development
  POSTGRES_USER: drkiq
  POSTGRES_PASSWORD: test_db_password
