kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mohamedelbahr/drkiq-nginx:latest
        ports:
        - name: http
          containerPort: 8020
          protocol: TCP